import streamlit as st 
import pandas as pd 

# =======================================
# MAIN PAGE HEADER
# =======================================
st.title('Welcome to Streamlit for Data Science')
st.header('Interactive Streamlit Components Demo')
st.markdown("""This app demonstrates various Streamlit components and their usage.  
Explore each section to learn more about Streamlit's capabilities.""")
st.markdown("---")

# =======================================
# SECTION 1: BASIC TEXT ELEMENTS
# =======================================
st.subheader('📝 Text Elements')
st.text('This is a simple text display')
st.markdown('**Markdown is supported** for _rich text formatting_')
st.markdown("""You can also use markdown for:
- Bullet points
- Code blocks
- And more!""")
st.markdown("---")

# =======================================
# SECTION 2: INTERACTIVE INPUT WIDGETS
# =======================================
st.subheader('🎛️ Interactive Input Widgets')

# Basic input widgets in columns for better organization
col1, col2 = st.columns(2)

with col1:
    # Button widget
    st.write("**Button Example:**")
    button = st.button('Click me')
    if button:
        st.success('Button clicked!')
    
    # Checkbox widget
    st.write("**Checkbox Example:**")
    checkbox = st.checkbox('I agree to the terms')
    if checkbox:
        st.success('Thank you for agreeing!')

with col2:
    # Selection widgets
    st.write("**Selection Widgets:**")
    radio = st.radio('Select one option:', ['Option 1', 'Option 2', 'Option 3'])
    st.write(f'You selected: {radio}')
    
    selectbox = st.selectbox('Choose from dropdown:', ['Option 1', 'Option 2', 'Option 3'])
    st.write(f'You chose: {selectbox}')

# Multi-select and slider
st.write("**Multiple Selection:**")
multiselect = st.multiselect('Select multiple options:', ['Option 1', 'Option 2', 'Option 3', 'Option 4'])
if multiselect:
    st.write(f'You selected: {", ".join(multiselect)}')

st.write("**Value Slider:**")
slider = st.slider('Select a value:', 0, 100, 50, help="Drag to select a value between 0 and 100")
st.write(f'Selected value: {slider}')

st.markdown("---")

# =======================================
# SECTION 3: DATA INPUT WIDGETS
# =======================================
st.subheader('📊 Data Input Widgets')

col1, col2 = st.columns(2)

with col1:
    # Text and number inputs
    text_input = st.text_input('Enter some text:', placeholder="Type here...")
    if text_input:
        st.write(f'You entered: {text_input}')
    
    number_input = st.number_input('Enter a number:', min_value=0, max_value=1000, value=50)
    st.write(f'Number entered: {number_input}')

with col2:
    # Date and time inputs
    date_input = st.date_input('Select a date:')
    st.write(f'Date selected: {date_input}')
    
    time_input = st.time_input('Select a time:')
    st.write(f'Time selected: {time_input}')

# File uploader and camera input
st.write("**File Upl`oad:**")
file_uploader = st.file_uploader('Upload a file', type=['csv', 'txt', 'pdf', 'jpg', 'png'])
if file_uploader is not None:
    st.success(f'File uploaded: {file_uploader.name}')

st.write("**Camera Input:**")
camera_input = st.camera_input('Take a photo')
if camera_input is not None:
    st.image(camera_input, caption="Captured Image")

# Color picker
st.write("**Color Selection:**")
color_picker = st.color_picker('Pick a color:', '#00BFFF')
st.markdown(f'<div style="background-color:{color_picker};padding:10px;border-radius:5px;">Selected color: {color_picker}</div>', unsafe_allow_html=True)

st.markdown("---")

# =======================================
# SECTION 4: PROGRESS INDICATORS
# =======================================
st.subheader('⏳ Progress Indicators')

# Progress bar example
st.write("**Progress Bar Example:**")
progress_bar = st.progress(0)
for i in range(100):
    progress_bar.progress(i + 1)

# Spinner example
st.write("**Spinner Example:**")
with st.spinner('Processing...'):
    st.success('Processing complete!')

# Balloons for celebration
st.write("**Celebration Effect:**")
if st.button("Celebrate!"):
    st.balloons()

st.markdown("---")

# =======================================
# SECTION 5: LAYOUT COMPONENTS
# =======================================
st.subheader('🔳 Layout Components')

# Sidebar components
with st.sidebar:
    st.title('Navigation Sidebar')
    st.markdown('Use this sidebar for navigation and filters')
    
    page = st.radio('Go to:', ['Home', 'Data Visualization', 'Settings'])
    st.markdown("---")
    
    st.subheader('Filters')
    st.checkbox('Show advanced options')
    st.slider('Filter threshold', 0, 100, 50)

# Columns layout example
st.write("**Columns Layout:**")
col1, col2, col3 = st.columns(3)
with col1:
    st.markdown("**Column 1**")
    st.info('This is column 1 content')
with col2:
    st.markdown("**Column 2**")
    st.warning('This is column 2 content')
with col3:
    st.markdown("**Column 3**")
    st.error('This is column 3 content')

# Tabs example
st.write("**Tabs Layout:**")
tab1, tab2, tab3 = st.tabs(['Data', 'Visualization', 'Settings'])
with tab1:
    st.markdown("**Data Tab**")
    st.write('This tab would contain your data tables')
    st.dataframe({'Name': ['John', 'Anna', 'Peter'], 'Age': [28, 34, 41]})
with tab2:
    st.markdown("**Visualization Tab**")
    st.write('This tab would contain your charts and plots')
    chart_data = pd.DataFrame({"col1": [1, 2, 3, 4], "col2": [10, 20, 30, 40]})
    st.line_chart(chart_data)
with tab3:
    st.markdown("**Settings Tab**")
    st.write('This tab would contain your app settings')
    st.checkbox('Enable dark mode')
    st.checkbox('Enable notifications')

# Footer
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown("---")
st.caption('Created with Streamlit for Data Science Learning')
st.markdown("---")
st.footer('This is a footer')
st.markdown(